FROM golang:1.26 AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY proto ./proto
COPY repository ./repository

ENV CGO_ENABLED=0

RUN go build -o /repository ./repository

FROM alpine:3.20

COPY --from=build /repository /repository

ENTRYPOINT ["/repository", "-config", "/config.yaml"]
