FROM golang:1.26 AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY proto ./proto
COPY parser ./parser

ENV CGO_ENABLED=0

RUN go build -o /parser ./parser

FROM alpine:3.20

COPY --from=build /parser /parser

ENTRYPOINT ["/parser", "-config", "/config.yaml"]
