FROM golang:1.26 AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY proto ./proto
COPY topology ./topology

ENV CGO_ENABLED=0

RUN go build -o /topology ./topology

FROM alpine:3.20

COPY --from=build /topology /topology

ENTRYPOINT ["/topology", "-config", "/config.yaml"]
