services:
  app:
    image: log-parser-app:latest
    build:
      context: log-services
      dockerfile: Dockerfile.app
    container_name: log-parser-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./log-services/app/config.yaml:/config.yaml
      - ./logs:/logs
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
      LOG_FILE_PATH: /logs/app.log
      APP_ADDRESS: :8080
      PARSER_GRPC_ADDRESS: parser:8080
      REPOSITORY_GRPC_ADDRESS: repository:8080
      TOPOLOGY_GRPC_ADDRESS: topology:8080
    depends_on:
      parser:
        condition: service_started
      repository:
        condition: service_started
      topology:
        condition: service_started

  parser:
    image: log-parser-parser:latest
    build:
      context: log-services
      dockerfile: Dockerfile.parser
    container_name: log-parser-parser
    restart: unless-stopped
    ports:
      - "28081:8080"
    volumes:
      - ./log-services/parser/config.yaml:/config.yaml
      - ./data:/data
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
      PARSER_ADDRESS: :8080

  repository:
    image: log-parser-repository:latest
    build:
      context: log-services
      dockerfile: Dockerfile.repository
    container_name: log-parser-repository
    restart: unless-stopped
    ports:
      - "28082:8080"
    volumes:
      - ./log-services/repository/config.yaml:/config.yaml
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
      REPOSITORY_ADDRESS: :8080
      DB_ADDRESS: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-postgres}?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

  topology:
    image: log-parser-topology:latest
    build:
      context: log-services
      dockerfile: Dockerfile.topology
    container_name: log-parser-topology
    restart: unless-stopped
    ports:
      - "28083:8080"
    volumes:
      - ./log-services/topology/config.yaml:/config.yaml
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
      TOPOLOGY_ADDRESS: :8080
      REPOSITORY_GRPC_ADDRESS: repository:8080
    depends_on:
      repository:
        condition: service_started

  postgres:
    image: postgres:16-alpine
    container_name: log-parser-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: log-parser-pgadmin
    restart: unless-stopped
    ports:
      - "18888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DISABLE_POSTFIX: "true"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres:
  pgadmin: