// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: repository/repository.proto

package repository

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogStatus int32

const (
	LogStatus_LOG_STATUS_UNSPECIFIED LogStatus = 0
	LogStatus_LOG_STATUS_PROCESSING  LogStatus = 1
	LogStatus_LOG_STATUS_PARSED      LogStatus = 2
	LogStatus_LOG_STATUS_FAILED      LogStatus = 3
)

// Enum value maps for LogStatus.
var (
	LogStatus_name = map[int32]string{
		0: "LOG_STATUS_UNSPECIFIED",
		1: "LOG_STATUS_PROCESSING",
		2: "LOG_STATUS_PARSED",
		3: "LOG_STATUS_FAILED",
	}
	LogStatus_value = map[string]int32{
		"LOG_STATUS_UNSPECIFIED": 0,
		"LOG_STATUS_PROCESSING":  1,
		"LOG_STATUS_PARSED":      2,
		"LOG_STATUS_FAILED":      3,
	}
)

func (x LogStatus) Enum() *LogStatus {
	p := new(LogStatus)
	*p = x
	return p
}

func (x LogStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_repository_repository_proto_enumTypes[0].Descriptor()
}

func (LogStatus) Type() protoreflect.EnumType {
	return &file_repository_repository_proto_enumTypes[0]
}

func (x LogStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogStatus.Descriptor instead.
func (LogStatus) EnumDescriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{0}
}

type CreateLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLogRequest) Reset() {
	*x = CreateLogRequest{}
	mi := &file_repository_repository_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLogRequest) ProtoMessage() {}

func (x *CreateLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLogRequest.ProtoReflect.Descriptor instead.
func (*CreateLogRequest) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLogRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type CreateLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         int64                  `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLogResponse) Reset() {
	*x = CreateLogResponse{}
	mi := &file_repository_repository_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLogResponse) ProtoMessage() {}

func (x *CreateLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLogResponse.ProtoReflect.Descriptor instead.
func (*CreateLogResponse) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLogResponse) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

type SaveParsedLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         int64                  `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	ParsedLog     *ParsedLog             `protobuf:"bytes,2,opt,name=parsed_log,json=parsedLog,proto3" json:"parsed_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveParsedLogRequest) Reset() {
	*x = SaveParsedLogRequest{}
	mi := &file_repository_repository_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveParsedLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveParsedLogRequest) ProtoMessage() {}

func (x *SaveParsedLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveParsedLogRequest.ProtoReflect.Descriptor instead.
func (*SaveParsedLogRequest) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{2}
}

func (x *SaveParsedLogRequest) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *SaveParsedLogRequest) GetParsedLog() *ParsedLog {
	if x != nil {
		return x.ParsedLog
	}
	return nil
}

type SaveParsedLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         int64                  `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	NodesCount    int32                  `protobuf:"varint,2,opt,name=nodes_count,json=nodesCount,proto3" json:"nodes_count,omitempty"`
	PortsCount    int32                  `protobuf:"varint,3,opt,name=ports_count,json=portsCount,proto3" json:"ports_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveParsedLogResponse) Reset() {
	*x = SaveParsedLogResponse{}
	mi := &file_repository_repository_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveParsedLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveParsedLogResponse) ProtoMessage() {}

func (x *SaveParsedLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveParsedLogResponse.ProtoReflect.Descriptor instead.
func (*SaveParsedLogResponse) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{3}
}

func (x *SaveParsedLogResponse) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *SaveParsedLogResponse) GetNodesCount() int32 {
	if x != nil {
		return x.NodesCount
	}
	return 0
}

func (x *SaveParsedLogResponse) GetPortsCount() int32 {
	if x != nil {
		return x.PortsCount
	}
	return 0
}

type FailLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         int64                  `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailLogRequest) Reset() {
	*x = FailLogRequest{}
	mi := &file_repository_repository_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailLogRequest) ProtoMessage() {}

func (x *FailLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailLogRequest.ProtoReflect.Descriptor instead.
func (*FailLogRequest) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{4}
}

func (x *FailLogRequest) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *FailLogRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ParsedLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*ParsedNode          `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Ports         []*ParsedPort          `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	NodesInfo     []*ParsedNodeInfo      `protobuf:"bytes,3,rep,name=nodes_info,json=nodesInfo,proto3" json:"nodes_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedLog) Reset() {
	*x = ParsedLog{}
	mi := &file_repository_repository_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedLog) ProtoMessage() {}

func (x *ParsedLog) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedLog.ProtoReflect.Descriptor instead.
func (*ParsedLog) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{5}
}

func (x *ParsedLog) GetNodes() []*ParsedNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ParsedLog) GetPorts() []*ParsedPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ParsedLog) GetNodesInfo() []*ParsedNodeInfo {
	if x != nil {
		return x.NodesInfo
	}
	return nil
}

type ParsedNode struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeGuid        string                 `protobuf:"bytes,1,opt,name=node_guid,json=nodeGuid,proto3" json:"node_guid,omitempty"`
	NodeDesc        string                 `protobuf:"bytes,2,opt,name=node_desc,json=nodeDesc,proto3" json:"node_desc,omitempty"`
	NodeType        int32                  `protobuf:"varint,3,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	NodeKind        string                 `protobuf:"bytes,4,opt,name=node_kind,json=nodeKind,proto3" json:"node_kind,omitempty"`
	NumPorts        int32                  `protobuf:"varint,5,opt,name=num_ports,json=numPorts,proto3" json:"num_ports,omitempty"`
	ClassVersion    int32                  `protobuf:"varint,6,opt,name=class_version,json=classVersion,proto3" json:"class_version,omitempty"`
	BaseVersion     int32                  `protobuf:"varint,7,opt,name=base_version,json=baseVersion,proto3" json:"base_version,omitempty"`
	SystemImageGuid string                 `protobuf:"bytes,8,opt,name=system_image_guid,json=systemImageGuid,proto3" json:"system_image_guid,omitempty"`
	PortGuid        string                 `protobuf:"bytes,9,opt,name=port_guid,json=portGuid,proto3" json:"port_guid,omitempty"`
	RawJson         string                 `protobuf:"bytes,10,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ParsedNode) Reset() {
	*x = ParsedNode{}
	mi := &file_repository_repository_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedNode) ProtoMessage() {}

func (x *ParsedNode) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedNode.ProtoReflect.Descriptor instead.
func (*ParsedNode) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{6}
}

func (x *ParsedNode) GetNodeGuid() string {
	if x != nil {
		return x.NodeGuid
	}
	return ""
}

func (x *ParsedNode) GetNodeDesc() string {
	if x != nil {
		return x.NodeDesc
	}
	return ""
}

func (x *ParsedNode) GetNodeType() int32 {
	if x != nil {
		return x.NodeType
	}
	return 0
}

func (x *ParsedNode) GetNodeKind() string {
	if x != nil {
		return x.NodeKind
	}
	return ""
}

func (x *ParsedNode) GetNumPorts() int32 {
	if x != nil {
		return x.NumPorts
	}
	return 0
}

func (x *ParsedNode) GetClassVersion() int32 {
	if x != nil {
		return x.ClassVersion
	}
	return 0
}

func (x *ParsedNode) GetBaseVersion() int32 {
	if x != nil {
		return x.BaseVersion
	}
	return 0
}

func (x *ParsedNode) GetSystemImageGuid() string {
	if x != nil {
		return x.SystemImageGuid
	}
	return ""
}

func (x *ParsedNode) GetPortGuid() string {
	if x != nil {
		return x.PortGuid
	}
	return ""
}

func (x *ParsedNode) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

type ParsedPort struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeGuid        string                 `protobuf:"bytes,1,opt,name=node_guid,json=nodeGuid,proto3" json:"node_guid,omitempty"`
	PortGuid        string                 `protobuf:"bytes,2,opt,name=port_guid,json=portGuid,proto3" json:"port_guid,omitempty"`
	PortNum         int32                  `protobuf:"varint,3,opt,name=port_num,json=portNum,proto3" json:"port_num,omitempty"`
	Lid             int32                  `protobuf:"varint,4,opt,name=lid,proto3" json:"lid,omitempty"`
	LocalPortNum    int32                  `protobuf:"varint,5,opt,name=local_port_num,json=localPortNum,proto3" json:"local_port_num,omitempty"`
	PortState       int32                  `protobuf:"varint,6,opt,name=port_state,json=portState,proto3" json:"port_state,omitempty"`
	PortPhyState    int32                  `protobuf:"varint,7,opt,name=port_phy_state,json=portPhyState,proto3" json:"port_phy_state,omitempty"`
	LinkWidthActive int32                  `protobuf:"varint,8,opt,name=link_width_active,json=linkWidthActive,proto3" json:"link_width_active,omitempty"`
	LinkSpeedActive int32                  `protobuf:"varint,9,opt,name=link_speed_active,json=linkSpeedActive,proto3" json:"link_speed_active,omitempty"`
	RawJson         string                 `protobuf:"bytes,10,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ParsedPort) Reset() {
	*x = ParsedPort{}
	mi := &file_repository_repository_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedPort) ProtoMessage() {}

func (x *ParsedPort) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedPort.ProtoReflect.Descriptor instead.
func (*ParsedPort) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{7}
}

func (x *ParsedPort) GetNodeGuid() string {
	if x != nil {
		return x.NodeGuid
	}
	return ""
}

func (x *ParsedPort) GetPortGuid() string {
	if x != nil {
		return x.PortGuid
	}
	return ""
}

func (x *ParsedPort) GetPortNum() int32 {
	if x != nil {
		return x.PortNum
	}
	return 0
}

func (x *ParsedPort) GetLid() int32 {
	if x != nil {
		return x.Lid
	}
	return 0
}

func (x *ParsedPort) GetLocalPortNum() int32 {
	if x != nil {
		return x.LocalPortNum
	}
	return 0
}

func (x *ParsedPort) GetPortState() int32 {
	if x != nil {
		return x.PortState
	}
	return 0
}

func (x *ParsedPort) GetPortPhyState() int32 {
	if x != nil {
		return x.PortPhyState
	}
	return 0
}

func (x *ParsedPort) GetLinkWidthActive() int32 {
	if x != nil {
		return x.LinkWidthActive
	}
	return 0
}

func (x *ParsedPort) GetLinkSpeedActive() int32 {
	if x != nil {
		return x.LinkSpeedActive
	}
	return 0
}

func (x *ParsedPort) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

type ParsedNodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeGuid      string                 `protobuf:"bytes,1,opt,name=node_guid,json=nodeGuid,proto3" json:"node_guid,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	PartNumber    string                 `protobuf:"bytes,3,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	Revision      string                 `protobuf:"bytes,4,opt,name=revision,proto3" json:"revision,omitempty"`
	ProductName   string                 `protobuf:"bytes,5,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	RawJson       string                 `protobuf:"bytes,6,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedNodeInfo) Reset() {
	*x = ParsedNodeInfo{}
	mi := &file_repository_repository_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedNodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedNodeInfo) ProtoMessage() {}

func (x *ParsedNodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedNodeInfo.ProtoReflect.Descriptor instead.
func (*ParsedNodeInfo) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{8}
}

func (x *ParsedNodeInfo) GetNodeGuid() string {
	if x != nil {
		return x.NodeGuid
	}
	return ""
}

func (x *ParsedNodeInfo) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *ParsedNodeInfo) GetPartNumber() string {
	if x != nil {
		return x.PartNumber
	}
	return ""
}

func (x *ParsedNodeInfo) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *ParsedNodeInfo) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ParsedNodeInfo) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

type GetLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         int64                  `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogRequest) Reset() {
	*x = GetLogRequest{}
	mi := &file_repository_repository_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogRequest) ProtoMessage() {}

func (x *GetLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogRequest.ProtoReflect.Descriptor instead.
func (*GetLogRequest) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{9}
}

func (x *GetLogRequest) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Status        LogStatus              `protobuf:"varint,3,opt,name=status,proto3,enum=repository.LogStatus" json:"status,omitempty"`
	NodesCount    int32                  `protobuf:"varint,4,opt,name=nodes_count,json=nodesCount,proto3" json:"nodes_count,omitempty"`
	PortsCount    int32                  `protobuf:"varint,5,opt,name=ports_count,json=portsCount,proto3" json:"ports_count,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	UploadedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	ParsedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=parsed_at,json=parsedAt,proto3" json:"parsed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_repository_repository_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{10}
}

func (x *Log) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Log) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Log) GetStatus() LogStatus {
	if x != nil {
		return x.Status
	}
	return LogStatus_LOG_STATUS_UNSPECIFIED
}

func (x *Log) GetNodesCount() int32 {
	if x != nil {
		return x.NodesCount
	}
	return 0
}

func (x *Log) GetPortsCount() int32 {
	if x != nil {
		return x.PortsCount
	}
	return 0
}

func (x *Log) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Log) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

func (x *Log) GetParsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ParsedAt
	}
	return nil
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_repository_repository_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{11}
}

func (x *GetNodeRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type GetPortsByNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortsByNodeRequest) Reset() {
	*x = GetPortsByNodeRequest{}
	mi := &file_repository_repository_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortsByNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortsByNodeRequest) ProtoMessage() {}

func (x *GetPortsByNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortsByNodeRequest.ProtoReflect.Descriptor instead.
func (*GetPortsByNodeRequest) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{12}
}

func (x *GetPortsByNodeRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type GetNodesByLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         int64                  `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesByLogRequest) Reset() {
	*x = GetNodesByLogRequest{}
	mi := &file_repository_repository_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesByLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesByLogRequest) ProtoMessage() {}

func (x *GetNodesByLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesByLogRequest.ProtoReflect.Descriptor instead.
func (*GetNodesByLogRequest) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{13}
}

func (x *GetNodesByLogRequest) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

type GetPortsByLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         int64                  `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortsByLogRequest) Reset() {
	*x = GetPortsByLogRequest{}
	mi := &file_repository_repository_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortsByLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortsByLogRequest) ProtoMessage() {}

func (x *GetPortsByLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortsByLogRequest.ProtoReflect.Descriptor instead.
func (*GetPortsByLogRequest) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{14}
}

func (x *GetPortsByLogRequest) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

type GetTopologyDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         int64                  `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopologyDataRequest) Reset() {
	*x = GetTopologyDataRequest{}
	mi := &file_repository_repository_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopologyDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyDataRequest) ProtoMessage() {}

func (x *GetTopologyDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyDataRequest.ProtoReflect.Descriptor instead.
func (*GetTopologyDataRequest) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{15}
}

func (x *GetTopologyDataRequest) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

type TopologyDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           *Log                   `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	Nodes         []*NodeDetails         `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Ports         []*Port                `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyDataResponse) Reset() {
	*x = TopologyDataResponse{}
	mi := &file_repository_repository_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyDataResponse) ProtoMessage() {}

func (x *TopologyDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyDataResponse.ProtoReflect.Descriptor instead.
func (*TopologyDataResponse) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{16}
}

func (x *TopologyDataResponse) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *TopologyDataResponse) GetNodes() []*NodeDetails {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *TopologyDataResponse) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

type NodeDetails struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LogId           int64                  `protobuf:"varint,2,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	NodeGuid        string                 `protobuf:"bytes,3,opt,name=node_guid,json=nodeGuid,proto3" json:"node_guid,omitempty"`
	NodeDesc        string                 `protobuf:"bytes,4,opt,name=node_desc,json=nodeDesc,proto3" json:"node_desc,omitempty"`
	NodeType        int32                  `protobuf:"varint,5,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	NodeKind        string                 `protobuf:"bytes,6,opt,name=node_kind,json=nodeKind,proto3" json:"node_kind,omitempty"`
	NumPorts        int32                  `protobuf:"varint,7,opt,name=num_ports,json=numPorts,proto3" json:"num_ports,omitempty"`
	ClassVersion    int32                  `protobuf:"varint,8,opt,name=class_version,json=classVersion,proto3" json:"class_version,omitempty"`
	BaseVersion     int32                  `protobuf:"varint,9,opt,name=base_version,json=baseVersion,proto3" json:"base_version,omitempty"`
	SystemImageGuid string                 `protobuf:"bytes,10,opt,name=system_image_guid,json=systemImageGuid,proto3" json:"system_image_guid,omitempty"`
	PortGuid        string                 `protobuf:"bytes,11,opt,name=port_guid,json=portGuid,proto3" json:"port_guid,omitempty"`
	Info            *NodeInfo              `protobuf:"bytes,12,opt,name=info,proto3" json:"info,omitempty"`
	RawJson         string                 `protobuf:"bytes,13,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeDetails) Reset() {
	*x = NodeDetails{}
	mi := &file_repository_repository_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDetails) ProtoMessage() {}

func (x *NodeDetails) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDetails.ProtoReflect.Descriptor instead.
func (*NodeDetails) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{17}
}

func (x *NodeDetails) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NodeDetails) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *NodeDetails) GetNodeGuid() string {
	if x != nil {
		return x.NodeGuid
	}
	return ""
}

func (x *NodeDetails) GetNodeDesc() string {
	if x != nil {
		return x.NodeDesc
	}
	return ""
}

func (x *NodeDetails) GetNodeType() int32 {
	if x != nil {
		return x.NodeType
	}
	return 0
}

func (x *NodeDetails) GetNodeKind() string {
	if x != nil {
		return x.NodeKind
	}
	return ""
}

func (x *NodeDetails) GetNumPorts() int32 {
	if x != nil {
		return x.NumPorts
	}
	return 0
}

func (x *NodeDetails) GetClassVersion() int32 {
	if x != nil {
		return x.ClassVersion
	}
	return 0
}

func (x *NodeDetails) GetBaseVersion() int32 {
	if x != nil {
		return x.BaseVersion
	}
	return 0
}

func (x *NodeDetails) GetSystemImageGuid() string {
	if x != nil {
		return x.SystemImageGuid
	}
	return ""
}

func (x *NodeDetails) GetPortGuid() string {
	if x != nil {
		return x.PortGuid
	}
	return ""
}

func (x *NodeDetails) GetInfo() *NodeInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *NodeDetails) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeId        int64                  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeGuid      string                 `protobuf:"bytes,3,opt,name=node_guid,json=nodeGuid,proto3" json:"node_guid,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,4,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	PartNumber    string                 `protobuf:"bytes,5,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	Revision      string                 `protobuf:"bytes,6,opt,name=revision,proto3" json:"revision,omitempty"`
	ProductName   string                 `protobuf:"bytes,7,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	RawJson       string                 `protobuf:"bytes,8,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_repository_repository_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{18}
}

func (x *NodeInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NodeInfo) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *NodeInfo) GetNodeGuid() string {
	if x != nil {
		return x.NodeGuid
	}
	return ""
}

func (x *NodeInfo) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *NodeInfo) GetPartNumber() string {
	if x != nil {
		return x.PartNumber
	}
	return ""
}

func (x *NodeInfo) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *NodeInfo) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *NodeInfo) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

type Port struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LogId           int64                  `protobuf:"varint,2,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	NodeId          int64                  `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeGuid        string                 `protobuf:"bytes,4,opt,name=node_guid,json=nodeGuid,proto3" json:"node_guid,omitempty"`
	PortGuid        string                 `protobuf:"bytes,5,opt,name=port_guid,json=portGuid,proto3" json:"port_guid,omitempty"`
	PortNum         int32                  `protobuf:"varint,6,opt,name=port_num,json=portNum,proto3" json:"port_num,omitempty"`
	Lid             int32                  `protobuf:"varint,7,opt,name=lid,proto3" json:"lid,omitempty"`
	LocalPortNum    int32                  `protobuf:"varint,8,opt,name=local_port_num,json=localPortNum,proto3" json:"local_port_num,omitempty"`
	PortState       int32                  `protobuf:"varint,9,opt,name=port_state,json=portState,proto3" json:"port_state,omitempty"`
	PortPhyState    int32                  `protobuf:"varint,10,opt,name=port_phy_state,json=portPhyState,proto3" json:"port_phy_state,omitempty"`
	LinkWidthActive int32                  `protobuf:"varint,11,opt,name=link_width_active,json=linkWidthActive,proto3" json:"link_width_active,omitempty"`
	LinkSpeedActive int32                  `protobuf:"varint,12,opt,name=link_speed_active,json=linkSpeedActive,proto3" json:"link_speed_active,omitempty"`
	RawJson         string                 `protobuf:"bytes,13,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_repository_repository_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{19}
}

func (x *Port) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Port) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *Port) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *Port) GetNodeGuid() string {
	if x != nil {
		return x.NodeGuid
	}
	return ""
}

func (x *Port) GetPortGuid() string {
	if x != nil {
		return x.PortGuid
	}
	return ""
}

func (x *Port) GetPortNum() int32 {
	if x != nil {
		return x.PortNum
	}
	return 0
}

func (x *Port) GetLid() int32 {
	if x != nil {
		return x.Lid
	}
	return 0
}

func (x *Port) GetLocalPortNum() int32 {
	if x != nil {
		return x.LocalPortNum
	}
	return 0
}

func (x *Port) GetPortState() int32 {
	if x != nil {
		return x.PortState
	}
	return 0
}

func (x *Port) GetPortPhyState() int32 {
	if x != nil {
		return x.PortPhyState
	}
	return 0
}

func (x *Port) GetLinkWidthActive() int32 {
	if x != nil {
		return x.LinkWidthActive
	}
	return 0
}

func (x *Port) GetLinkSpeedActive() int32 {
	if x != nil {
		return x.LinkSpeedActive
	}
	return 0
}

func (x *Port) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

type NodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeDetails         `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodesResponse) Reset() {
	*x = NodesResponse{}
	mi := &file_repository_repository_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodesResponse) ProtoMessage() {}

func (x *NodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodesResponse.ProtoReflect.Descriptor instead.
func (*NodesResponse) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{20}
}

func (x *NodesResponse) GetNodes() []*NodeDetails {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type PortsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ports         []*Port                `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortsResponse) Reset() {
	*x = PortsResponse{}
	mi := &file_repository_repository_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortsResponse) ProtoMessage() {}

func (x *PortsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortsResponse.ProtoReflect.Descriptor instead.
func (*PortsResponse) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{21}
}

func (x *PortsResponse) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

var File_repository_repository_proto protoreflect.FileDescriptor

const file_repository_repository_proto_rawDesc = "" +
	"\n" +
	"\x1brepository/repository.proto\x12\n" +
	"repository\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"/\n" +
	"\x10CreateLogRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"*\n" +
	"\x11CreateLogResponse\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\x03R\x05logId\"c\n" +
	"\x14SaveParsedLogRequest\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\x03R\x05logId\x124\n" +
	"\n" +
	"parsed_log\x18\x02 \x01(\v2\x15.repository.ParsedLogR\tparsedLog\"p\n" +
	"\x15SaveParsedLogResponse\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\x03R\x05logId\x12\x1f\n" +
	"\vnodes_count\x18\x02 \x01(\x05R\n" +
	"nodesCount\x12\x1f\n" +
	"\vports_count\x18\x03 \x01(\x05R\n" +
	"portsCount\"=\n" +
	"\x0eFailLogRequest\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\x03R\x05logId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa2\x01\n" +
	"\tParsedLog\x12,\n" +
	"\x05nodes\x18\x01 \x03(\v2\x16.repository.ParsedNodeR\x05nodes\x12,\n" +
	"\x05ports\x18\x02 \x03(\v2\x16.repository.ParsedPortR\x05ports\x129\n" +
	"\n" +
	"nodes_info\x18\x03 \x03(\v2\x1a.repository.ParsedNodeInfoR\tnodesInfo\"\xc9\x02\n" +
	"\n" +
	"ParsedNode\x12\x1b\n" +
	"\tnode_guid\x18\x01 \x01(\tR\bnodeGuid\x12\x1b\n" +
	"\tnode_desc\x18\x02 \x01(\tR\bnodeDesc\x12\x1b\n" +
	"\tnode_type\x18\x03 \x01(\x05R\bnodeType\x12\x1b\n" +
	"\tnode_kind\x18\x04 \x01(\tR\bnodeKind\x12\x1b\n" +
	"\tnum_ports\x18\x05 \x01(\x05R\bnumPorts\x12#\n" +
	"\rclass_version\x18\x06 \x01(\x05R\fclassVersion\x12!\n" +
	"\fbase_version\x18\a \x01(\x05R\vbaseVersion\x12*\n" +
	"\x11system_image_guid\x18\b \x01(\tR\x0fsystemImageGuid\x12\x1b\n" +
	"\tport_guid\x18\t \x01(\tR\bportGuid\x12\x19\n" +
	"\braw_json\x18\n" +
	" \x01(\tR\arawJson\"\xd1\x02\n" +
	"\n" +
	"ParsedPort\x12\x1b\n" +
	"\tnode_guid\x18\x01 \x01(\tR\bnodeGuid\x12\x1b\n" +
	"\tport_guid\x18\x02 \x01(\tR\bportGuid\x12\x19\n" +
	"\bport_num\x18\x03 \x01(\x05R\aportNum\x12\x10\n" +
	"\x03lid\x18\x04 \x01(\x05R\x03lid\x12$\n" +
	"\x0elocal_port_num\x18\x05 \x01(\x05R\flocalPortNum\x12\x1d\n" +
	"\n" +
	"port_state\x18\x06 \x01(\x05R\tportState\x12$\n" +
	"\x0eport_phy_state\x18\a \x01(\x05R\fportPhyState\x12*\n" +
	"\x11link_width_active\x18\b \x01(\x05R\x0flinkWidthActive\x12*\n" +
	"\x11link_speed_active\x18\t \x01(\x05R\x0flinkSpeedActive\x12\x19\n" +
	"\braw_json\x18\n" +
	" \x01(\tR\arawJson\"\xcd\x01\n" +
	"\x0eParsedNodeInfo\x12\x1b\n" +
	"\tnode_guid\x18\x01 \x01(\tR\bnodeGuid\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\x1f\n" +
	"\vpart_number\x18\x03 \x01(\tR\n" +
	"partNumber\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\tR\brevision\x12!\n" +
	"\fproduct_name\x18\x05 \x01(\tR\vproductName\x12\x19\n" +
	"\braw_json\x18\x06 \x01(\tR\arawJson\"&\n" +
	"\rGetLogRequest\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\x03R\x05logId\"\xaf\x02\n" +
	"\x03Log\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.repository.LogStatusR\x06status\x12\x1f\n" +
	"\vnodes_count\x18\x04 \x01(\x05R\n" +
	"nodesCount\x12\x1f\n" +
	"\vports_count\x18\x05 \x01(\x05R\n" +
	"portsCount\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12;\n" +
	"\vuploaded_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAt\x127\n" +
	"\tparsed_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bparsedAt\")\n" +
	"\x0eGetNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\"0\n" +
	"\x15GetPortsByNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\"-\n" +
	"\x14GetNodesByLogRequest\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\x03R\x05logId\"-\n" +
	"\x14GetPortsByLogRequest\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\x03R\x05logId\"/\n" +
	"\x16GetTopologyDataRequest\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\x03R\x05logId\"\x90\x01\n" +
	"\x14TopologyDataResponse\x12!\n" +
	"\x03log\x18\x01 \x01(\v2\x0f.repository.LogR\x03log\x12-\n" +
	"\x05nodes\x18\x02 \x03(\v2\x17.repository.NodeDetailsR\x05nodes\x12&\n" +
	"\x05ports\x18\x03 \x03(\v2\x10.repository.PortR\x05ports\"\x9b\x03\n" +
	"\vNodeDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06log_id\x18\x02 \x01(\x03R\x05logId\x12\x1b\n" +
	"\tnode_guid\x18\x03 \x01(\tR\bnodeGuid\x12\x1b\n" +
	"\tnode_desc\x18\x04 \x01(\tR\bnodeDesc\x12\x1b\n" +
	"\tnode_type\x18\x05 \x01(\x05R\bnodeType\x12\x1b\n" +
	"\tnode_kind\x18\x06 \x01(\tR\bnodeKind\x12\x1b\n" +
	"\tnum_ports\x18\a \x01(\x05R\bnumPorts\x12#\n" +
	"\rclass_version\x18\b \x01(\x05R\fclassVersion\x12!\n" +
	"\fbase_version\x18\t \x01(\x05R\vbaseVersion\x12*\n" +
	"\x11system_image_guid\x18\n" +
	" \x01(\tR\x0fsystemImageGuid\x12\x1b\n" +
	"\tport_guid\x18\v \x01(\tR\bportGuid\x12(\n" +
	"\x04info\x18\f \x01(\v2\x14.repository.NodeInfoR\x04info\x12\x19\n" +
	"\braw_json\x18\r \x01(\tR\arawJson\"\xf0\x01\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x03R\x06nodeId\x12\x1b\n" +
	"\tnode_guid\x18\x03 \x01(\tR\bnodeGuid\x12#\n" +
	"\rserial_number\x18\x04 \x01(\tR\fserialNumber\x12\x1f\n" +
	"\vpart_number\x18\x05 \x01(\tR\n" +
	"partNumber\x12\x1a\n" +
	"\brevision\x18\x06 \x01(\tR\brevision\x12!\n" +
	"\fproduct_name\x18\a \x01(\tR\vproductName\x12\x19\n" +
	"\braw_json\x18\b \x01(\tR\arawJson\"\x8b\x03\n" +
	"\x04Port\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06log_id\x18\x02 \x01(\x03R\x05logId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\x03R\x06nodeId\x12\x1b\n" +
	"\tnode_guid\x18\x04 \x01(\tR\bnodeGuid\x12\x1b\n" +
	"\tport_guid\x18\x05 \x01(\tR\bportGuid\x12\x19\n" +
	"\bport_num\x18\x06 \x01(\x05R\aportNum\x12\x10\n" +
	"\x03lid\x18\a \x01(\x05R\x03lid\x12$\n" +
	"\x0elocal_port_num\x18\b \x01(\x05R\flocalPortNum\x12\x1d\n" +
	"\n" +
	"port_state\x18\t \x01(\x05R\tportState\x12$\n" +
	"\x0eport_phy_state\x18\n" +
	" \x01(\x05R\fportPhyState\x12*\n" +
	"\x11link_width_active\x18\v \x01(\x05R\x0flinkWidthActive\x12*\n" +
	"\x11link_speed_active\x18\f \x01(\x05R\x0flinkSpeedActive\x12\x19\n" +
	"\braw_json\x18\r \x01(\tR\arawJson\">\n" +
	"\rNodesResponse\x12-\n" +
	"\x05nodes\x18\x01 \x03(\v2\x17.repository.NodeDetailsR\x05nodes\"7\n" +
	"\rPortsResponse\x12&\n" +
	"\x05ports\x18\x01 \x03(\v2\x10.repository.PortR\x05ports*p\n" +
	"\tLogStatus\x12\x1a\n" +
	"\x16LOG_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15LOG_STATUS_PROCESSING\x10\x01\x12\x15\n" +
	"\x11LOG_STATUS_PARSED\x10\x02\x12\x15\n" +
	"\x11LOG_STATUS_FAILED\x10\x032\xde\x05\n" +
	"\n" +
	"Repository\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\tCreateLog\x12\x1c.repository.CreateLogRequest\x1a\x1d.repository.CreateLogResponse\x12T\n" +
	"\rSaveParsedLog\x12 .repository.SaveParsedLogRequest\x1a!.repository.SaveParsedLogResponse\x12=\n" +
	"\aFailLog\x12\x1a.repository.FailLogRequest\x1a\x16.google.protobuf.Empty\x124\n" +
	"\x06GetLog\x12\x19.repository.GetLogRequest\x1a\x0f.repository.Log\x12>\n" +
	"\aGetNode\x12\x1a.repository.GetNodeRequest\x1a\x17.repository.NodeDetails\x12N\n" +
	"\x0eGetPortsByNode\x12!.repository.GetPortsByNodeRequest\x1a\x19.repository.PortsResponse\x12L\n" +
	"\rGetNodesByLog\x12 .repository.GetNodesByLogRequest\x1a\x19.repository.NodesResponse\x12L\n" +
	"\rGetPortsByLog\x12 .repository.GetPortsByLogRequest\x1a\x19.repository.PortsResponse\x12W\n" +
	"\x0fGetTopologyData\x12\".repository.GetTopologyDataRequest\x1a .repository.TopologyDataResponseBMZKgithub.com/voronkov44/microservice-log-parser/log-services/proto/repositoryb\x06proto3"

var (
	file_repository_repository_proto_rawDescOnce sync.Once
	file_repository_repository_proto_rawDescData []byte
)

func file_repository_repository_proto_rawDescGZIP() []byte {
	file_repository_repository_proto_rawDescOnce.Do(func() {
		file_repository_repository_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repository_repository_proto_rawDesc), len(file_repository_repository_proto_rawDesc)))
	})
	return file_repository_repository_proto_rawDescData
}

var file_repository_repository_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_repository_repository_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_repository_repository_proto_goTypes = []any{
	(LogStatus)(0),                 // 0: repository.LogStatus
	(*CreateLogRequest)(nil),       // 1: repository.CreateLogRequest
	(*CreateLogResponse)(nil),      // 2: repository.CreateLogResponse
	(*SaveParsedLogRequest)(nil),   // 3: repository.SaveParsedLogRequest
	(*SaveParsedLogResponse)(nil),  // 4: repository.SaveParsedLogResponse
	(*FailLogRequest)(nil),         // 5: repository.FailLogRequest
	(*ParsedLog)(nil),              // 6: repository.ParsedLog
	(*ParsedNode)(nil),             // 7: repository.ParsedNode
	(*ParsedPort)(nil),             // 8: repository.ParsedPort
	(*ParsedNodeInfo)(nil),         // 9: repository.ParsedNodeInfo
	(*GetLogRequest)(nil),          // 10: repository.GetLogRequest
	(*Log)(nil),                    // 11: repository.Log
	(*GetNodeRequest)(nil),         // 12: repository.GetNodeRequest
	(*GetPortsByNodeRequest)(nil),  // 13: repository.GetPortsByNodeRequest
	(*GetNodesByLogRequest)(nil),   // 14: repository.GetNodesByLogRequest
	(*GetPortsByLogRequest)(nil),   // 15: repository.GetPortsByLogRequest
	(*GetTopologyDataRequest)(nil), // 16: repository.GetTopologyDataRequest
	(*TopologyDataResponse)(nil),   // 17: repository.TopologyDataResponse
	(*NodeDetails)(nil),            // 18: repository.NodeDetails
	(*NodeInfo)(nil),               // 19: repository.NodeInfo
	(*Port)(nil),                   // 20: repository.Port
	(*NodesResponse)(nil),          // 21: repository.NodesResponse
	(*PortsResponse)(nil),          // 22: repository.PortsResponse
	(*timestamppb.Timestamp)(nil),  // 23: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 24: google.protobuf.Empty
}
var file_repository_repository_proto_depIdxs = []int32{
	6,  // 0: repository.SaveParsedLogRequest.parsed_log:type_name -> repository.ParsedLog
	7,  // 1: repository.ParsedLog.nodes:type_name -> repository.ParsedNode
	8,  // 2: repository.ParsedLog.ports:type_name -> repository.ParsedPort
	9,  // 3: repository.ParsedLog.nodes_info:type_name -> repository.ParsedNodeInfo
	0,  // 4: repository.Log.status:type_name -> repository.LogStatus
	23, // 5: repository.Log.uploaded_at:type_name -> google.protobuf.Timestamp
	23, // 6: repository.Log.parsed_at:type_name -> google.protobuf.Timestamp
	11, // 7: repository.TopologyDataResponse.log:type_name -> repository.Log
	18, // 8: repository.TopologyDataResponse.nodes:type_name -> repository.NodeDetails
	20, // 9: repository.TopologyDataResponse.ports:type_name -> repository.Port
	19, // 10: repository.NodeDetails.info:type_name -> repository.NodeInfo
	18, // 11: repository.NodesResponse.nodes:type_name -> repository.NodeDetails
	20, // 12: repository.PortsResponse.ports:type_name -> repository.Port
	24, // 13: repository.Repository.Ping:input_type -> google.protobuf.Empty
	1,  // 14: repository.Repository.CreateLog:input_type -> repository.CreateLogRequest
	3,  // 15: repository.Repository.SaveParsedLog:input_type -> repository.SaveParsedLogRequest
	5,  // 16: repository.Repository.FailLog:input_type -> repository.FailLogRequest
	10, // 17: repository.Repository.GetLog:input_type -> repository.GetLogRequest
	12, // 18: repository.Repository.GetNode:input_type -> repository.GetNodeRequest
	13, // 19: repository.Repository.GetPortsByNode:input_type -> repository.GetPortsByNodeRequest
	14, // 20: repository.Repository.GetNodesByLog:input_type -> repository.GetNodesByLogRequest
	15, // 21: repository.Repository.GetPortsByLog:input_type -> repository.GetPortsByLogRequest
	16, // 22: repository.Repository.GetTopologyData:input_type -> repository.GetTopologyDataRequest
	24, // 23: repository.Repository.Ping:output_type -> google.protobuf.Empty
	2,  // 24: repository.Repository.CreateLog:output_type -> repository.CreateLogResponse
	4,  // 25: repository.Repository.SaveParsedLog:output_type -> repository.SaveParsedLogResponse
	24, // 26: repository.Repository.FailLog:output_type -> google.protobuf.Empty
	11, // 27: repository.Repository.GetLog:output_type -> repository.Log
	18, // 28: repository.Repository.GetNode:output_type -> repository.NodeDetails
	22, // 29: repository.Repository.GetPortsByNode:output_type -> repository.PortsResponse
	21, // 30: repository.Repository.GetNodesByLog:output_type -> repository.NodesResponse
	22, // 31: repository.Repository.GetPortsByLog:output_type -> repository.PortsResponse
	17, // 32: repository.Repository.GetTopologyData:output_type -> repository.TopologyDataResponse
	23, // [23:33] is the sub-list for method output_type
	13, // [13:23] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_repository_repository_proto_init() }
func file_repository_repository_proto_init() {
	if File_repository_repository_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repository_repository_proto_rawDesc), len(file_repository_repository_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_repository_repository_proto_goTypes,
		DependencyIndexes: file_repository_repository_proto_depIdxs,
		EnumInfos:         file_repository_repository_proto_enumTypes,
		MessageInfos:      file_repository_repository_proto_msgTypes,
	}.Build()
	File_repository_repository_proto = out.File
	file_repository_repository_proto_goTypes = nil
	file_repository_repository_proto_depIdxs = nil
}
