// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: repository/repository.proto

package repository

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Repository_Ping_FullMethodName           = "/repository.Repository/Ping"
	Repository_CreateLog_FullMethodName      = "/repository.Repository/CreateLog"
	Repository_SaveParsedLog_FullMethodName  = "/repository.Repository/SaveParsedLog"
	Repository_FailLog_FullMethodName        = "/repository.Repository/FailLog"
	Repository_GetLog_FullMethodName         = "/repository.Repository/GetLog"
	Repository_GetNode_FullMethodName        = "/repository.Repository/GetNode"
	Repository_GetPortsByNode_FullMethodName = "/repository.Repository/GetPortsByNode"
	Repository_GetNodesByLog_FullMethodName  = "/repository.Repository/GetNodesByLog"
	Repository_GetPortsByLog_FullMethodName  = "/repository.Repository/GetPortsByLog"
)

// RepositoryClient is the client API for Repository service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RepositoryClient interface {
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateLog(ctx context.Context, in *CreateLogRequest, opts ...grpc.CallOption) (*CreateLogResponse, error)
	SaveParsedLog(ctx context.Context, in *SaveParsedLogRequest, opts ...grpc.CallOption) (*SaveParsedLogResponse, error)
	FailLog(ctx context.Context, in *FailLogRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetLog(ctx context.Context, in *GetLogRequest, opts ...grpc.CallOption) (*Log, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*NodeDetails, error)
	GetPortsByNode(ctx context.Context, in *GetPortsByNodeRequest, opts ...grpc.CallOption) (*PortsResponse, error)
	GetNodesByLog(ctx context.Context, in *GetNodesByLogRequest, opts ...grpc.CallOption) (*NodesResponse, error)
	GetPortsByLog(ctx context.Context, in *GetPortsByLogRequest, opts ...grpc.CallOption) (*PortsResponse, error)
}

type repositoryClient struct {
	cc grpc.ClientConnInterface
}

func NewRepositoryClient(cc grpc.ClientConnInterface) RepositoryClient {
	return &repositoryClient{cc}
}

func (c *repositoryClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Repository_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) CreateLog(ctx context.Context, in *CreateLogRequest, opts ...grpc.CallOption) (*CreateLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLogResponse)
	err := c.cc.Invoke(ctx, Repository_CreateLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) SaveParsedLog(ctx context.Context, in *SaveParsedLogRequest, opts ...grpc.CallOption) (*SaveParsedLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveParsedLogResponse)
	err := c.cc.Invoke(ctx, Repository_SaveParsedLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) FailLog(ctx context.Context, in *FailLogRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Repository_FailLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) GetLog(ctx context.Context, in *GetLogRequest, opts ...grpc.CallOption) (*Log, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Log)
	err := c.cc.Invoke(ctx, Repository_GetLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*NodeDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeDetails)
	err := c.cc.Invoke(ctx, Repository_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) GetPortsByNode(ctx context.Context, in *GetPortsByNodeRequest, opts ...grpc.CallOption) (*PortsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortsResponse)
	err := c.cc.Invoke(ctx, Repository_GetPortsByNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) GetNodesByLog(ctx context.Context, in *GetNodesByLogRequest, opts ...grpc.CallOption) (*NodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodesResponse)
	err := c.cc.Invoke(ctx, Repository_GetNodesByLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) GetPortsByLog(ctx context.Context, in *GetPortsByLogRequest, opts ...grpc.CallOption) (*PortsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortsResponse)
	err := c.cc.Invoke(ctx, Repository_GetPortsByLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RepositoryServer is the server API for Repository service.
// All implementations must embed UnimplementedRepositoryServer
// for forward compatibility.
type RepositoryServer interface {
	Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	CreateLog(context.Context, *CreateLogRequest) (*CreateLogResponse, error)
	SaveParsedLog(context.Context, *SaveParsedLogRequest) (*SaveParsedLogResponse, error)
	FailLog(context.Context, *FailLogRequest) (*emptypb.Empty, error)
	GetLog(context.Context, *GetLogRequest) (*Log, error)
	GetNode(context.Context, *GetNodeRequest) (*NodeDetails, error)
	GetPortsByNode(context.Context, *GetPortsByNodeRequest) (*PortsResponse, error)
	GetNodesByLog(context.Context, *GetNodesByLogRequest) (*NodesResponse, error)
	GetPortsByLog(context.Context, *GetPortsByLogRequest) (*PortsResponse, error)
	mustEmbedUnimplementedRepositoryServer()
}

// UnimplementedRepositoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRepositoryServer struct{}

func (UnimplementedRepositoryServer) Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRepositoryServer) CreateLog(context.Context, *CreateLogRequest) (*CreateLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLog not implemented")
}
func (UnimplementedRepositoryServer) SaveParsedLog(context.Context, *SaveParsedLogRequest) (*SaveParsedLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveParsedLog not implemented")
}
func (UnimplementedRepositoryServer) FailLog(context.Context, *FailLogRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FailLog not implemented")
}
func (UnimplementedRepositoryServer) GetLog(context.Context, *GetLogRequest) (*Log, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLog not implemented")
}
func (UnimplementedRepositoryServer) GetNode(context.Context, *GetNodeRequest) (*NodeDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedRepositoryServer) GetPortsByNode(context.Context, *GetPortsByNodeRequest) (*PortsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPortsByNode not implemented")
}
func (UnimplementedRepositoryServer) GetNodesByLog(context.Context, *GetNodesByLogRequest) (*NodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodesByLog not implemented")
}
func (UnimplementedRepositoryServer) GetPortsByLog(context.Context, *GetPortsByLogRequest) (*PortsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPortsByLog not implemented")
}
func (UnimplementedRepositoryServer) mustEmbedUnimplementedRepositoryServer() {}
func (UnimplementedRepositoryServer) testEmbeddedByValue()                    {}

// UnsafeRepositoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RepositoryServer will
// result in compilation errors.
type UnsafeRepositoryServer interface {
	mustEmbedUnimplementedRepositoryServer()
}

func RegisterRepositoryServer(s grpc.ServiceRegistrar, srv RepositoryServer) {
	// If the following call pancis, it indicates UnimplementedRepositoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Repository_ServiceDesc, srv)
}

func _Repository_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Repository_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_CreateLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).CreateLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Repository_CreateLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).CreateLog(ctx, req.(*CreateLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_SaveParsedLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveParsedLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).SaveParsedLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Repository_SaveParsedLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).SaveParsedLog(ctx, req.(*SaveParsedLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_FailLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).FailLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Repository_FailLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).FailLog(ctx, req.(*FailLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_GetLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).GetLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Repository_GetLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).GetLog(ctx, req.(*GetLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Repository_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_GetPortsByNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortsByNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).GetPortsByNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Repository_GetPortsByNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).GetPortsByNode(ctx, req.(*GetPortsByNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_GetNodesByLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodesByLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).GetNodesByLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Repository_GetNodesByLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).GetNodesByLog(ctx, req.(*GetNodesByLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_GetPortsByLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortsByLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).GetPortsByLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Repository_GetPortsByLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).GetPortsByLog(ctx, req.(*GetPortsByLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Repository_ServiceDesc is the grpc.ServiceDesc for Repository service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Repository_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "repository.Repository",
	HandlerType: (*RepositoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Repository_Ping_Handler,
		},
		{
			MethodName: "CreateLog",
			Handler:    _Repository_CreateLog_Handler,
		},
		{
			MethodName: "SaveParsedLog",
			Handler:    _Repository_SaveParsedLog_Handler,
		},
		{
			MethodName: "FailLog",
			Handler:    _Repository_FailLog_Handler,
		},
		{
			MethodName: "GetLog",
			Handler:    _Repository_GetLog_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _Repository_GetNode_Handler,
		},
		{
			MethodName: "GetPortsByNode",
			Handler:    _Repository_GetPortsByNode_Handler,
		},
		{
			MethodName: "GetNodesByLog",
			Handler:    _Repository_GetNodesByLog_Handler,
		},
		{
			MethodName: "GetPortsByLog",
			Handler:    _Repository_GetPortsByLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "repository/repository.proto",
}
