// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/parser/parser.proto

package parser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_proto_parser_parser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parser_parser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_proto_parser_parser_proto_rawDescGZIP(), []int{0}
}

func (x *ParseRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ParseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           *ParsedLog             `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_proto_parser_parser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parser_parser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_proto_parser_parser_proto_rawDescGZIP(), []int{1}
}

func (x *ParseResponse) GetLog() *ParsedLog {
	if x != nil {
		return x.Log
	}
	return nil
}

type ParsedLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Ports         []*Port                `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	NodesInfo     []*NodeInfo            `protobuf:"bytes,3,rep,name=nodes_info,json=nodesInfo,proto3" json:"nodes_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedLog) Reset() {
	*x = ParsedLog{}
	mi := &file_proto_parser_parser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedLog) ProtoMessage() {}

func (x *ParsedLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parser_parser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedLog.ProtoReflect.Descriptor instead.
func (*ParsedLog) Descriptor() ([]byte, []int) {
	return file_proto_parser_parser_proto_rawDescGZIP(), []int{2}
}

func (x *ParsedLog) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ParsedLog) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ParsedLog) GetNodesInfo() []*NodeInfo {
	if x != nil {
		return x.NodesInfo
	}
	return nil
}

type Node struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeGuid        string                 `protobuf:"bytes,1,opt,name=node_guid,json=nodeGuid,proto3" json:"node_guid,omitempty"`
	NodeDesc        string                 `protobuf:"bytes,2,opt,name=node_desc,json=nodeDesc,proto3" json:"node_desc,omitempty"`
	NodeType        int32                  `protobuf:"varint,3,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	NodeKind        string                 `protobuf:"bytes,4,opt,name=node_kind,json=nodeKind,proto3" json:"node_kind,omitempty"`
	NumPorts        int32                  `protobuf:"varint,5,opt,name=num_ports,json=numPorts,proto3" json:"num_ports,omitempty"`
	ClassVersion    int32                  `protobuf:"varint,6,opt,name=class_version,json=classVersion,proto3" json:"class_version,omitempty"`
	BaseVersion     int32                  `protobuf:"varint,7,opt,name=base_version,json=baseVersion,proto3" json:"base_version,omitempty"`
	SystemImageGuid string                 `protobuf:"bytes,8,opt,name=system_image_guid,json=systemImageGuid,proto3" json:"system_image_guid,omitempty"`
	PortGuid        string                 `protobuf:"bytes,9,opt,name=port_guid,json=portGuid,proto3" json:"port_guid,omitempty"`
	RawJson         string                 `protobuf:"bytes,10,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_proto_parser_parser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parser_parser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_proto_parser_parser_proto_rawDescGZIP(), []int{3}
}

func (x *Node) GetNodeGuid() string {
	if x != nil {
		return x.NodeGuid
	}
	return ""
}

func (x *Node) GetNodeDesc() string {
	if x != nil {
		return x.NodeDesc
	}
	return ""
}

func (x *Node) GetNodeType() int32 {
	if x != nil {
		return x.NodeType
	}
	return 0
}

func (x *Node) GetNodeKind() string {
	if x != nil {
		return x.NodeKind
	}
	return ""
}

func (x *Node) GetNumPorts() int32 {
	if x != nil {
		return x.NumPorts
	}
	return 0
}

func (x *Node) GetClassVersion() int32 {
	if x != nil {
		return x.ClassVersion
	}
	return 0
}

func (x *Node) GetBaseVersion() int32 {
	if x != nil {
		return x.BaseVersion
	}
	return 0
}

func (x *Node) GetSystemImageGuid() string {
	if x != nil {
		return x.SystemImageGuid
	}
	return ""
}

func (x *Node) GetPortGuid() string {
	if x != nil {
		return x.PortGuid
	}
	return ""
}

func (x *Node) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

type Port struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeGuid        string                 `protobuf:"bytes,1,opt,name=node_guid,json=nodeGuid,proto3" json:"node_guid,omitempty"`
	PortGuid        string                 `protobuf:"bytes,2,opt,name=port_guid,json=portGuid,proto3" json:"port_guid,omitempty"`
	PortNum         int32                  `protobuf:"varint,3,opt,name=port_num,json=portNum,proto3" json:"port_num,omitempty"`
	Lid             int32                  `protobuf:"varint,4,opt,name=lid,proto3" json:"lid,omitempty"`
	LocalPortNum    int32                  `protobuf:"varint,5,opt,name=local_port_num,json=localPortNum,proto3" json:"local_port_num,omitempty"`
	PortState       int32                  `protobuf:"varint,6,opt,name=port_state,json=portState,proto3" json:"port_state,omitempty"`
	PortPhyState    int32                  `protobuf:"varint,7,opt,name=port_phy_state,json=portPhyState,proto3" json:"port_phy_state,omitempty"`
	LinkWidthActive int32                  `protobuf:"varint,8,opt,name=link_width_active,json=linkWidthActive,proto3" json:"link_width_active,omitempty"`
	LinkSpeedActive int32                  `protobuf:"varint,9,opt,name=link_speed_active,json=linkSpeedActive,proto3" json:"link_speed_active,omitempty"`
	RawJson         string                 `protobuf:"bytes,10,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_proto_parser_parser_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parser_parser_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_proto_parser_parser_proto_rawDescGZIP(), []int{4}
}

func (x *Port) GetNodeGuid() string {
	if x != nil {
		return x.NodeGuid
	}
	return ""
}

func (x *Port) GetPortGuid() string {
	if x != nil {
		return x.PortGuid
	}
	return ""
}

func (x *Port) GetPortNum() int32 {
	if x != nil {
		return x.PortNum
	}
	return 0
}

func (x *Port) GetLid() int32 {
	if x != nil {
		return x.Lid
	}
	return 0
}

func (x *Port) GetLocalPortNum() int32 {
	if x != nil {
		return x.LocalPortNum
	}
	return 0
}

func (x *Port) GetPortState() int32 {
	if x != nil {
		return x.PortState
	}
	return 0
}

func (x *Port) GetPortPhyState() int32 {
	if x != nil {
		return x.PortPhyState
	}
	return 0
}

func (x *Port) GetLinkWidthActive() int32 {
	if x != nil {
		return x.LinkWidthActive
	}
	return 0
}

func (x *Port) GetLinkSpeedActive() int32 {
	if x != nil {
		return x.LinkSpeedActive
	}
	return 0
}

func (x *Port) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeGuid      string                 `protobuf:"bytes,1,opt,name=node_guid,json=nodeGuid,proto3" json:"node_guid,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	PartNumber    string                 `protobuf:"bytes,3,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	Revision      string                 `protobuf:"bytes,4,opt,name=revision,proto3" json:"revision,omitempty"`
	ProductName   string                 `protobuf:"bytes,5,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	RawJson       string                 `protobuf:"bytes,6,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_proto_parser_parser_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parser_parser_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_parser_parser_proto_rawDescGZIP(), []int{5}
}

func (x *NodeInfo) GetNodeGuid() string {
	if x != nil {
		return x.NodeGuid
	}
	return ""
}

func (x *NodeInfo) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *NodeInfo) GetPartNumber() string {
	if x != nil {
		return x.PartNumber
	}
	return ""
}

func (x *NodeInfo) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *NodeInfo) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *NodeInfo) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

var File_proto_parser_parser_proto protoreflect.FileDescriptor

const file_proto_parser_parser_proto_rawDesc = "" +
	"\n" +
	"\x19proto/parser/parser.proto\x12\x06parser\x1a\x1bgoogle/protobuf/empty.proto\"\"\n" +
	"\fParseRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"4\n" +
	"\rParseResponse\x12#\n" +
	"\x03log\x18\x01 \x01(\v2\x11.parser.ParsedLogR\x03log\"\x84\x01\n" +
	"\tParsedLog\x12\"\n" +
	"\x05nodes\x18\x01 \x03(\v2\f.parser.NodeR\x05nodes\x12\"\n" +
	"\x05ports\x18\x02 \x03(\v2\f.parser.PortR\x05ports\x12/\n" +
	"\n" +
	"nodes_info\x18\x03 \x03(\v2\x10.parser.NodeInfoR\tnodesInfo\"\xc3\x02\n" +
	"\x04Node\x12\x1b\n" +
	"\tnode_guid\x18\x01 \x01(\tR\bnodeGuid\x12\x1b\n" +
	"\tnode_desc\x18\x02 \x01(\tR\bnodeDesc\x12\x1b\n" +
	"\tnode_type\x18\x03 \x01(\x05R\bnodeType\x12\x1b\n" +
	"\tnode_kind\x18\x04 \x01(\tR\bnodeKind\x12\x1b\n" +
	"\tnum_ports\x18\x05 \x01(\x05R\bnumPorts\x12#\n" +
	"\rclass_version\x18\x06 \x01(\x05R\fclassVersion\x12!\n" +
	"\fbase_version\x18\a \x01(\x05R\vbaseVersion\x12*\n" +
	"\x11system_image_guid\x18\b \x01(\tR\x0fsystemImageGuid\x12\x1b\n" +
	"\tport_guid\x18\t \x01(\tR\bportGuid\x12\x19\n" +
	"\braw_json\x18\n" +
	" \x01(\tR\arawJson\"\xcb\x02\n" +
	"\x04Port\x12\x1b\n" +
	"\tnode_guid\x18\x01 \x01(\tR\bnodeGuid\x12\x1b\n" +
	"\tport_guid\x18\x02 \x01(\tR\bportGuid\x12\x19\n" +
	"\bport_num\x18\x03 \x01(\x05R\aportNum\x12\x10\n" +
	"\x03lid\x18\x04 \x01(\x05R\x03lid\x12$\n" +
	"\x0elocal_port_num\x18\x05 \x01(\x05R\flocalPortNum\x12\x1d\n" +
	"\n" +
	"port_state\x18\x06 \x01(\x05R\tportState\x12$\n" +
	"\x0eport_phy_state\x18\a \x01(\x05R\fportPhyState\x12*\n" +
	"\x11link_width_active\x18\b \x01(\x05R\x0flinkWidthActive\x12*\n" +
	"\x11link_speed_active\x18\t \x01(\x05R\x0flinkSpeedActive\x12\x19\n" +
	"\braw_json\x18\n" +
	" \x01(\tR\arawJson\"\xc7\x01\n" +
	"\bNodeInfo\x12\x1b\n" +
	"\tnode_guid\x18\x01 \x01(\tR\bnodeGuid\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\x1f\n" +
	"\vpart_number\x18\x03 \x01(\tR\n" +
	"partNumber\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\tR\brevision\x12!\n" +
	"\fproduct_name\x18\x05 \x01(\tR\vproductName\x12\x19\n" +
	"\braw_json\x18\x06 \x01(\tR\arawJson2v\n" +
	"\x06Parser\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x124\n" +
	"\x05Parse\x12\x14.parser.ParseRequest\x1a\x15.parser.ParseResponseBIZGgithub.com/voronkov44/microservice-log-parser/log-services/proto/parserb\x06proto3"

var (
	file_proto_parser_parser_proto_rawDescOnce sync.Once
	file_proto_parser_parser_proto_rawDescData []byte
)

func file_proto_parser_parser_proto_rawDescGZIP() []byte {
	file_proto_parser_parser_proto_rawDescOnce.Do(func() {
		file_proto_parser_parser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_parser_parser_proto_rawDesc), len(file_proto_parser_parser_proto_rawDesc)))
	})
	return file_proto_parser_parser_proto_rawDescData
}

var file_proto_parser_parser_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_parser_parser_proto_goTypes = []any{
	(*ParseRequest)(nil),  // 0: parser.ParseRequest
	(*ParseResponse)(nil), // 1: parser.ParseResponse
	(*ParsedLog)(nil),     // 2: parser.ParsedLog
	(*Node)(nil),          // 3: parser.Node
	(*Port)(nil),          // 4: parser.Port
	(*NodeInfo)(nil),      // 5: parser.NodeInfo
	(*emptypb.Empty)(nil), // 6: google.protobuf.Empty
}
var file_proto_parser_parser_proto_depIdxs = []int32{
	2, // 0: parser.ParseResponse.log:type_name -> parser.ParsedLog
	3, // 1: parser.ParsedLog.nodes:type_name -> parser.Node
	4, // 2: parser.ParsedLog.ports:type_name -> parser.Port
	5, // 3: parser.ParsedLog.nodes_info:type_name -> parser.NodeInfo
	6, // 4: parser.Parser.Ping:input_type -> google.protobuf.Empty
	0, // 5: parser.Parser.Parse:input_type -> parser.ParseRequest
	6, // 6: parser.Parser.Ping:output_type -> google.protobuf.Empty
	1, // 7: parser.Parser.Parse:output_type -> parser.ParseResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_parser_parser_proto_init() }
func file_proto_parser_parser_proto_init() {
	if File_proto_parser_parser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_parser_parser_proto_rawDesc), len(file_proto_parser_parser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_parser_parser_proto_goTypes,
		DependencyIndexes: file_proto_parser_parser_proto_depIdxs,
		MessageInfos:      file_proto_parser_parser_proto_msgTypes,
	}.Build()
	File_proto_parser_parser_proto = out.File
	file_proto_parser_parser_proto_goTypes = nil
	file_proto_parser_parser_proto_depIdxs = nil
}
